<h2>Edit User</h2>

<p>
    <a class="btn btn-success btn-sm" href="<?= $this->url('bpl-admin/user-management') ?>">
        Go to User Management
    </a>
</p>

<p>
    <strong>
        User : <?= $this->user->getEmail().'('.$this->user->getId().')' ?>
    </strong>
</p>

<?= $this->partial('bpl-admin/form', ['form' => $this->form]) ?>
<?= $this->edited == true ? '<p>User edited successfully !</p>' : '' ?>