<h2>Welcome <?= $this->getUserEmail() ?> </h2>
<p></p>
<p>
    <a class="btn btn-success" href="<?= $this->url('bpl-admin/access-management',['action' => 'controller']) ?>">
        Go to Controller Access Management
    </a>
</p>

<p>
    <a class="btn btn-success" href="<?= $this->url('bpl-admin/access-management',['action' => 'resource']) ?>">
        Go to Resource Access Management
    </a>
</p>
