<?php

$this->form = $form;
$this->form->prepare();

echo $this->form()->openTag($this->form);

foreach ($this->form as $element) {
    if ($element instanceof \Laminas\Form\Fieldset) {
        displayFieldset($element, $this);
    } else {
        echo '<div class="form_element">' . PHP_EOL;
        echo $this->formRow()->render($element) . PHP_EOL;
        echo '</div>' . PHP_EOL;
    }
}
echo $this->form()->closeTag();

function displayFieldset(\Laminas\Form\Fieldset $f, $renderer) {
    $isEmptyFieldset = sizeof($f->getElements());
    if ($isEmptyFieldset) {
        echo '<fieldset class="form-group border p-3">'
        . '<legend style="font-size: 18px; font-weight: bold;">'
        . $f->getName()
        . '</legend>';
    }
    foreach ($f as $em) {
        if ($em instanceof \Laminas\Form\Fieldset) {
            displayFieldset($em, $renderer);
        } else {
            echo '<div class="form_element">' . PHP_EOL;
            if ($em instanceof \Laminas\Form\Element\Collection) {
                if ($em->getCount() > 0) {
                    echo $renderer->formCollection()->render($em) . PHP_EOL;
                }
            } else {
                echo $renderer->formRow()->render($em) . PHP_EOL;
            }
            echo '</div>' . PHP_EOL;
        }
    }
    echo '</fieldset>';
}
